# =============================================================================
# 📍 TOPOLOGIES - DISCOVERY CONSTANTS (PATCHED for Beauty CRM)
# =============================================================================

# Import manifest filename from local manifest folder (self-contained)
load("./manifest/constants.star", "MANIFEST_FILENAME", "MANIFEST_FILENAME_YAML")

# Re-export for consumers of this module
MANIFEST_FILENAME = MANIFEST_FILENAME
MANIFEST_FILENAME_YAML = MANIFEST_FILENAME_YAML

# NOTE: These paths are resolved relative to the TILTFILE directory (project root)
# NOT relative to this module's location
SERVICES_ROOT = "services/product"
SERVICES_ROOT_PREFIX = ""

# Phase 2: Universal Discovery - Scan roots configuration
# Each root is scanned for service.json files
# Paths are relative to PROJECT_ROOT (where Tiltfile is located)
DISCOVERY_SCAN_ROOTS = [
    SERVICES_ROOT,                           # services/product/*/*/
    "services/platform",                     # services/platform/*/*/
    "shared-product-engineering",            # shared-product-engineering/*/
    "cli-platform-engineering",              # cli-platform-engineering/*/
]

# Phase 2: Explicit domain extraction patterns for each root type
# Documents HOW to extract domain from different directory structures
SCAN_ROOT_PATTERNS = {
    SERVICES_ROOT: {
        "domain_depth": -3,  # services/product/{DOMAIN}/{service}/
        "description": "Domain-grouped services (product)"
    },
    "services/platform": {
        "domain_depth": -2,  # services/platform/{SERVICE}/ (flat)
        "description": "Flat platform services"
    },
    "shared-product-engineering": {
        "domain_depth": -2,  # shared-product-engineering/{SERVICE}/ (flat)
        "description": "Shared libraries (flat)"
    },
    "cli-platform-engineering": {
        "domain_depth": -2,  # cli-platform-engineering/{SERVICE}/ (flat)
        "description": "CLI tools (flat)"
    },
}

# Phase 2: Performance guardrails (Phase 3 optimization baseline)
MAX_SCAN_TIMEOUT_MS = 5000    # 5 seconds per root (warn if exceeded)
MAX_MANIFESTS_PER_ROOT = 50   # Warn if root has more manifests

# Autogenerated files directory (relative to this file's location)
PRODUCT_SNAPSHOT_DIR = "../../product_autogenerated_service_manifests"

PRODUCT_SNAPSHOT_FILES = {
    "services": "services.autogenerated.star",
    "dependencies": "service_dependencies.autogenerated.star",
    "aliases": "service_aliases.autogenerated.star",
    "paths": "service_paths.autogenerated.star",
    "index": "index.autogenerated.star",
    "readme": "README.autogenerated.md",
}

PRODUCT_TOPOLOGY_DIR = "../../product_autogenerated_services_list"
PRODUCT_DOMAINS_INDEX_FILE = "domains.autogenerated.star"
PRODUCT_DOMAIN_SERVICES_FILE = "services.autogenerated.star"
