load("../manifest/parser.star", "extract_domain_from_path")
load("../manifest/loader.star", "ManifestLoader")
load("./manifest/loading.star", "get_default_syncs_for_type")
load("../../../../spec.master", "OUT_OF_SCOPE_DOMAINS")
load("../manifest/constants.star", "MANIFEST_FILENAME", "MANIFEST_FILENAME_YAML")
load("../../../../.tilt/TILT_SERVICE_DEFAULTS.star", "BASE_PORT_FRONTEND", "BASE_PORT_BACKEND", "get_default_port")

# Phase 1: Use json_manifest_scanner for manifest discovery (enables Phase 2 multi-source discovery)
load("./json_manifest_scanner.star", "discover_json_manifests")
load("./constants.star", 
     "SERVICES_ROOT",
     "DISCOVERY_SCAN_ROOTS",
     "SCAN_ROOT_PATTERNS",
     "MAX_SCAN_TIMEOUT_MS",
     "MAX_MANIFESTS_PER_ROOT")

# Phase 1.5: Validation integration for stability
load("./validation.star", "validate")

# Phase 2: Root overlap validation (prevents duplicate scanning from misconfiguration)
def _validate_scan_roots(roots):
    """Ensure no root is a subdirectory of another."""
    sorted_roots = sorted(roots, key=len)
    for i, root in enumerate(sorted_roots):
        for other in sorted_roots[i+1:]:
            root_normalized = root.rstrip("/") + "/"
            other_normalized = other.rstrip("/") + "/"
            if other_normalized.startswith(root_normalized):
                print("⚠️  Warning: {} is subdirectory of {}".format(other, root))

# Built-in functions available in Tilt (no load needed)
# read_json, local are built-in

# Define locally since parser.star exports this as private
def _determine_app_type(manifest, service_path):
    """
    Determine app type from manifest or service path.
    """
    # Check if manifest has explicit appType
    if manifest.get("appType") in ["frontend", "backend", "library", "migrator", "sdk", "worker"]:
        return manifest["appType"]
    
    # Extract from path
    dir_name = service_path.split("/")[-1] if service_path else ""
    
    if dir_name.endswith("-frontend"):
        return "frontend"
    if dir_name.endswith("-backend"):
        return "backend"
    if dir_name.endswith("-migrator"):
        return "migrator"
    if dir_name.endswith("-sdk"):
        return "sdk"
    
    # Default to backend
    return "backend"

def _normalize_manifest(manifest, service_path):
    """
    Normalize manifest to discovery resource format.
    Phase 5: Works with both legacy and new manifest system normalized manifests.
    """
    # If manifest is already normalized by new system, use it directly
    if manifest.get("_normalized") or manifest.get("syncs"):
        # Extract fields from normalized manifest
        app_name = manifest.get("appName", service_path.split("/")[-1])
        app_type = manifest.get("appType", _determine_app_type(manifest, service_path))
        stack = manifest.get("stack") or manifest.get("domain") or extract_domain_from_path(service_path)
        port = manifest.get("port", BASE_PORT_BACKEND if app_type == "backend" else BASE_PORT_FRONTEND)
    else:
        # Legacy path: compute fields
        app_name = manifest.get("appName", service_path.split("/")[-1])
        app_type = _determine_app_type(manifest, service_path)
        stack = manifest.get("stack") or manifest.get("domain") or extract_domain_from_path(service_path)
        port = manifest.get("port", BASE_PORT_BACKEND if app_type == "backend" else BASE_PORT_FRONTEND)
    
    features = manifest.get("features", [])
    syncs = manifest.get("syncs", get_default_syncs_for_type(app_type, features))
    dockerfile = manifest.get("dockerfile", "autogenerated/Dockerfile.app.autogenerated")

    resource = {
        "name": app_name,
        "dockerfile": app_name + "/" + dockerfile,
        "syncs": syncs,
        "port": port,
        "stack": stack,
        "_manifest": manifest.get("_manifest", manifest),
        "_service_path": service_path,
    }

    if app_type == "frontend":
        resource["frontend"] = True
        resource["backendName"] = manifest.get("backendName", app_name.replace("-frontend", "-backend"))

    if manifest.get("target_path"):
        resource["target_path"] = manifest["target_path"]
    if manifest.get("prisma_client_path"):
        resource["prisma_client_path"] = manifest["prisma_client_path"]
    if manifest.get("registry_host"):
        resource["registry_host"] = manifest["registry_host"]
    if manifest.get("start_command"):
        resource["start_command"] = manifest["start_command"]

    return resource


def _get_domain_path(domain):
    return "services/product/" + domain


def initialize_discovery(cache, second_pass=False):
    """
    Initialize discovery cache by scanning for manifest files.
    
    Args:
        cache: Dictionary to populate with discovery data
        second_pass: If True, this is the second initialization pass (for logging only)
    """
    if cache.get("initialized"):
        return
    
    # Scan for services from JSON manifests (source of truth)
    # YAML files are only for Tilt resource tracking, not data parsing
    if second_pass:
        print("📄 Pass 2/2: Preparing Tilt resources...")
        print("  └─ Re-loading from cache and creating local resources")
    else:
        print("📄 Pass 1/2: Building service registry from service.json...")
        print("  └─ Scanning, validating, and caching service definitions")
    
    services = _scan_services()
    
    # Build dependency graph and aliases
    dependencies = {}
    aliases = {}
    path_map = {}
    
    for svc in services:
        name = svc.get("name", "")
        path = svc.get("path", "")
        
        # Map name to path
        if name:
            aliases[name] = path
            path_map[path] = name
            
            # Extract dependencies from manifest
            manifest = svc.get("_manifest", {})
            deps = manifest.get("internalDependencies", [])
            if deps:
                dependencies[name] = deps
    
    # Populate cache
    cache["app_services"] = services
    cache["service_dependencies"] = dependencies
    cache["service_aliases"] = aliases
    cache["service_path_map"] = path_map
    cache["domain_configs"] = {}
    cache["initialized"] = True
    if second_pass:
        cache["second_pass"] = True


def _scan_services_from_yaml():
    """
    DEPRECATED: Do not use for data loading. JSON is the source of truth.
    
    This function is kept only for Tilt resource tracking purposes.
    YAML files are generated from JSON for local_resource() creation only.
    For data loading, always use _scan_services() which loads JSON directly.
    """
    print("⚠️  WARNING: _scan_services_from_yaml is deprecated. Use _scan_services() for data loading.")
    return []


def _scan_services():
    """
    FIRST PASS: Scan for all services with JSON manifest files from multiple roots.
    Phase 2: Multi-root discovery with validation, deduplication, and explicit domain extraction.
    Returns list of service dictionaries.
    """
    services = []
    
    # Phase 1.5: Track validation stats and skipped domains for discovery summary
    validation_stats = {
        "total_manifests": 0,
        "valid_manifests": 0,
        "manifests_with_warnings": 0,
        "total_warnings": 0,
    }
    skipped_domains = {}  # Track skipped domains for summary
    
    # Phase 2: Validate scan roots don't overlap (prevents duplicate scanning)
    _validate_scan_roots(DISCOVERY_SCAN_ROOTS)
    
    # Phase 2: Scan all root directories and collect manifest paths
    all_manifest_paths = []  # Collect from all roots
    
    # Show consolidated loading message
    total_roots = len(DISCOVERY_SCAN_ROOTS)
    print("📦 Loading from {} scan roots...".format(total_roots))
    
    for root in DISCOVERY_SCAN_ROOTS:
        # Use json_manifest_scanner.discover_json_manifests() to find all manifest files
        paths = discover_json_manifests(root)
        
        if paths:
            # Phase 2: Performance guardrails - warn if root is too large
            if len(paths) > MAX_MANIFESTS_PER_ROOT:
                print("  ⚠️  Large root: {} has {} manifests (max: {})".format(
                    root, len(paths), MAX_MANIFESTS_PER_ROOT))
            
            # Only show in verbose mode
            if os.environ.get('TILT_LOG_LEVEL') == 'verbose':
                print("  📁 Scanned {} manifests from {}".format(len(paths), root))
            all_manifest_paths.extend(paths)
    
    # Phase 2: Deduplicate by path (in case of overlaps between roots)
    seen_paths = {}
    manifest_paths = []
    for path in all_manifest_paths:
        if path not in seen_paths:
            seen_paths[path] = True
            manifest_paths.append(path)
    
    if not manifest_paths:
        return services
    
    for manifest_path in manifest_paths:
        # manifest_path already stripped by json_manifest_scanner
        
        # Parse manifest using proper loader (handles JSON and YAML)
        # First, extract service path from manifest path
        full_service_path = manifest_path.rsplit("/", 1)[0]
        
        # Normalize path to be relative (strip leading / if present)
        # Docker build context requires relative paths
        if full_service_path.startswith('/'):
            full_service_path = full_service_path[1:]
        
        # Use the loader which handles both JSON and YAML and normalizes format
        load_result = ManifestLoader.load_from_file(manifest_path)
        if load_result.error:
            print("Error loading manifest: " + load_result.error)
            continue
        
        manifest = load_result.manifest
        if not manifest:
            continue
        
        # Phase 1.5: Validate manifest structure and content
        validation_stats["total_manifests"] += 1
        validation_issues = validate(manifest)
        if validation_issues:
            validation_stats["manifests_with_warnings"] += 1
            validation_stats["total_warnings"] += len(validation_issues)
            # Log all validation issues with file path for context
            for issue in validation_issues:
                print("⚠️  Validation: " + manifest_path + ": " + issue)
            # Lenient mode: log warnings but continue discovery
            # (Strict mode could fail here with: continue)
        else:
            validation_stats["valid_manifests"] += 1
        
        # Skip out-of-scope domains for alpha (defined in spec.master)
        stack = manifest.get("stack") or manifest.get("domain", "")
        if stack in OUT_OF_SCOPE_DOMAINS:
            # Track skipped domain for summary instead of printing immediately
            if stack not in skipped_domains:
                skipped_domains[stack] = 0
            skipped_domains[stack] += 1
            continue
        
        # Convert relative path to project-root-relative path
        # manifest_path is like: ../../../../services/product/{domain}/{service}/manifest.json
        # We want: services/product/{domain}/{service}
        if manifest_path.startswith("../../../../"):
            project_relative_path = manifest_path[12:]  # Remove "../../../../" prefix
        else:
            project_relative_path = manifest_path
        
        # Extract service info from the project-relative path
        # Format: services/product/{domain}/{service}/" + MANIFEST_FILENAME, 
        path_parts = project_relative_path.split("/")
        if len(path_parts) < 2:
            continue
        
        service_dir = path_parts[-2]  # e.g., "appointment-management-frontend"
        
        # Phase 2: Use explicit domain extraction patterns
        # Determine which root this manifest came from
        matching_root = None
        for root in DISCOVERY_SCAN_ROOTS:
            if manifest_path.startswith(root):
                matching_root = root
                break
        
        # Use configured pattern or default to parent folder
        pattern = SCAN_ROOT_PATTERNS.get(matching_root, {"domain_depth": -2})
        depth = pattern["domain_depth"]
        
        # Extract domain based on configured depth
        if abs(depth) <= len(path_parts):
            domain_dir = path_parts[depth]
        else:
            domain_dir = path_parts[-2] if len(path_parts) >= 2 else ""  # Fallback to parent
        
        # Build paths relative to project root (for use by other modules)
        base_path = "/".join(path_parts[:-2])  # e.g., "services/product/appointment"
        service_path = base_path  # This is the DOMAIN path
        full_service_path = project_relative_path.rsplit("/", 1)[0]  # Full path to service
        
        # Normalize path to be relative (strip leading / if present)
        # Docker build context requires relative paths
        if full_service_path.startswith('/'):
            full_service_path = full_service_path[1:]
        
        app_name = manifest.get("appName", service_dir)
        app_type = manifest.get("appType", "backend")
        stack = manifest.get("stack") or manifest.get("domain", domain_dir)
        port = manifest.get("port", get_default_port(app_type))
        features = manifest.get("features", [])
        
        # Build resource entry
        # dockerfile path must be full path from project root
        # Use custom dockerfile from manifest if specified, otherwise use autogenerated default
        custom_dockerfile = manifest.get("dockerfile")
        if custom_dockerfile:
            dockerfile_path = full_service_path + "/" + custom_dockerfile
        else:
            dockerfile_path = full_service_path + "/autogenerated/Dockerfile.app.autogenerated"
        
        resource = {
            "name": app_name,
            "dockerfile": dockerfile_path,
            "syncs": get_default_syncs_for_type(app_type, features),
            "port": port,
            "stack": stack,
            "_manifest": manifest,
            "_service_path": full_service_path,
        }
        
        # Add frontend-specific fields
        if app_type == "frontend":
            resource["frontend"] = True
            resource["backendName"] = manifest.get("backendName", app_name.replace("-frontend", "-backend"))
        
        # Build service entry
        service_key = stack if stack else app_name.replace("-" + app_type, "")
        
        # Check if service already exists (merge resources for same domain)
        existing_service = None
        for svc in services:
            if svc["name"] == service_key:
                existing_service = svc
                break
        
        if existing_service:
            # Add resource to existing service
            existing_service["resources"].append(resource)
            existing_service["labels"].append("app." + app_name)
        else:
            # Create new service entry
            service = {
                "name": service_key,
                "path": service_path,
                "labels": ["app." + app_name] if app_name else [],
                "resources": [resource],
            }
            services.append(service)
    
    # Phase 1.5: Print consolidated discovery summary
    if validation_stats["total_manifests"] > 0:
        # Calculate total skipped manually (sum() not available in Starlark)
        total_skipped = 0
        for count in skipped_domains.values():
            total_skipped += count
        print("✅ {} services loaded ({} valid, {} skipped)".format(
            validation_stats["total_manifests"],
            validation_stats["valid_manifests"],
            total_skipped))
        
        if validation_stats["manifests_with_warnings"] > 0:
            print("  ⚠️  {} manifest(s) with {} validation warning(s)".format(
                validation_stats["manifests_with_warnings"], 
                validation_stats["total_warnings"]))
        
        if skipped_domains and os.environ.get('TILT_LOG_LEVEL') == 'verbose':
            skipped_list = ", ".join(["{} ({})".format(d, c) for d, c in skipped_domains.items()])
            print("  📋 Focus mode skipped: {}".format(skipped_list))
    
    return services
