# =============================================================================
# 📋 MANIFEST CONSTANTS (Self-Contained)
# =============================================================================
# Path: manifest/constants.star
# Purpose: Define manifest filename patterns and constants
# =============================================================================

# Manifest filenames
MANIFEST_FILENAME = "service.json"
MANIFEST_FILENAME_YAML = "service.yaml"
MANIFEST_FILENAME_NEW = "service.json"
MANIFEST_FILENAME_NEW_YAML = "service.yaml"

# File patterns
MANIFEST_PATTERN = "*.json"

# Config filenames
PACKAGE_CONFIG_FILENAMES = ["package.json", "bun.lock"]
GENERATED_CONFIG_FILENAMES = ["tsconfig.json", "vite.config.ts"]

# Autogenerated paths
AUTOGENERATED_CONFIG_PATHS = ["autogenerated/"]

# Manifest defaults
MANIFEST_DEFAULTS = {
    "appType": "backend",
    "runtime": "bun",
    "port": 4000,
    "replicas": 1,
}

# Valid app types
VALID_APP_TYPES = ["backend", "frontend", "library", "migrator", "sdk", "worker"]

# Default syncs
DEFAULT_SYNCS = ["src", "prisma"]

# Runtime configs
RUNTIME_CONFIGS = {
    "bun": {"port_env": "PORT", "command": "bun run start"},
    "node": {"port_env": "PORT", "command": "node dist/index.js"},
}

# Traefik defaults
TRAEFIK_DEFAULTS = {
    "entrypoint": "web",
    "scheme": "http",
}

# Service name patterns
SERVICE_NAME_PATTERNS = {
    "backend": "{domain}-management-backend",
    "frontend": "{domain}-management-frontend",
}

# Validation thresholds
VALIDATION_THRESHOLDS = {
    "min_port": 3000,
    "max_port": 9999,
    "min_replicas": 1,
    "max_replicas": 10,
}

# Valid domains (common ones)
VALID_DOMAINS = [
    "identity", "appointment", "salon", "staff", "inventory", 
    "payment", "treatment", "reporting", "website", "gdpr"
]

# Valid features
VALID_FEATURES = ["nats", "prisma", "vite-node", "websocket", "cron"]

# Port ranges
PORT_RANGES = {
    "frontend_start": 3000,
    "frontend_end": 3999,
    "backend_start": 4000,
    "backend_end": 4999,
}

# Struct for grouped exports
ManifestConstants = struct(
    MANIFEST_FILENAME = MANIFEST_FILENAME,
    MANIFEST_FILENAME_YAML = MANIFEST_FILENAME_YAML,
    MANIFEST_FILENAME_NEW = MANIFEST_FILENAME_NEW,
    MANIFEST_FILENAME_NEW_YAML = MANIFEST_FILENAME_NEW_YAML,
    MANIFEST_PATTERN = MANIFEST_PATTERN,
    PACKAGE_CONFIG_FILENAMES = PACKAGE_CONFIG_FILENAMES,
    GENERATED_CONFIG_FILENAMES = GENERATED_CONFIG_FILENAMES,
    AUTOGENERATED_CONFIG_PATHS = AUTOGENERATED_CONFIG_PATHS,
    MANIFEST_DEFAULTS = MANIFEST_DEFAULTS,
    VALID_APP_TYPES = VALID_APP_TYPES,
    DEFAULT_SYNCS = DEFAULT_SYNCS,
    RUNTIME_CONFIGS = RUNTIME_CONFIGS,
    TRAEFIK_DEFAULTS = TRAEFIK_DEFAULTS,
    SERVICE_NAME_PATTERNS = SERVICE_NAME_PATTERNS,
    VALIDATION_THRESHOLDS = VALIDATION_THRESHOLDS,
    VALID_DOMAINS = VALID_DOMAINS,
    VALID_FEATURES = VALID_FEATURES,
    PORT_RANGES = PORT_RANGES,
)
