# =============================================================================
# 📋 TILT SDK - MANIFEST CONSTANTS (DEPRECATED)
# =============================================================================
# Path: .tilt/topologies/tilt/discovery/manifest/constants.star
# Purpose: DEPRECATED - Re-export from new location for backward compatibility
# 
# ⚠️  WARNING: This file is deprecated and will be removed in Phase 5
#    Use: load("../../manifest/__init__.star", "Manifest")
#    Instead of: load("./manifest/constants.star", "...")
# =============================================================================

# Re-export all constants from new location
load("../../../tilt/manifest/constants.star",
    "MANIFEST_FILENAME",
    "MANIFEST_PATTERN",
    "PACKAGE_CONFIG_FILENAMES",
    "GENERATED_CONFIG_FILENAMES",
    "AUTOGENERATED_CONFIG_PATHS",
    "MANIFEST_DEFAULTS",
    "VALID_APP_TYPES",
    "DEFAULT_SYNCS",
    "RUNTIME_CONFIGS",
    "TRAEFIK_DEFAULTS",
    "SERVICE_NAME_PATTERNS",
    "VALIDATION_THRESHOLDS",
    "ManifestConstants",
)
load("../../../../../.tilt/TILT_DISCOVERY.star",
    "VALID_DOMAINS",
    "VALID_FEATURES",
    "PORT_RANGES",
)

# Re-export for backward compatibility
# All exports are identical to the new location for seamless migration
